#!/usr/bin/env python3
"""Write the Phase81P official-method audit from pinned local checkouts."""
from __future__ import annotations
import datetime, hashlib, json, os, subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "outputs/iclr27_phase81p/audit/literature_audit.json"

def head(repo: str) -> str:
    try: return subprocess.check_output(["git", "-C", str(ROOT / repo), "rev-parse", "HEAD"], text=True).strip()
    except Exception: return "not_checked_out"

def license_name(repo: str) -> str:
    p = ROOT / repo
    for name in ("LICENSE", "LICENSE.md", "LICENSE.txt"):
        if (p / name).is_file():
            text=(p/name).read_text(errors="ignore")[:1000].lower()
            if "apache" in text: return "Apache-2.0"
            if "mit license" in text or "permission is hereby granted" in text: return "MIT"
            return "present_unclassified"
    return "not_found_in_checkout"

def main():
    methods = [
      {"name":"OVTR","year":2025,"venue":"ICLR","repo":"https://github.com/jinyanglii/OVTR","paper":"https://arxiv.org/abs/2503.10616","local_repo":"third_party/research_refs_phase4n/OVTR","commit":head("third_party/research_refs_phase4n/OVTR"),"license":license_name("third_party/research_refs_phase4n/OVTR"),"inputs":"RGB frames, detector/query features and optional CLIP/category branch","outputs":"persistent query tracks and open-vocabulary scores","online_causal":True,"persistent_query":True,"cross_video_correspondence":False,"uses_text_category_id":"yes in semantic/CIP paths; isolate for TrackOCD","reusable":"deformable query decoder, RuntimeTrackerBase, full-sequence TAO path","reject":"text/category logits and semantic heads cannot enter TrackOCD inference","official_command":"sh tools/ovtr_ovmot_eval_e15_val.sh"},
      {"name":"MOTIP-2","year":2025,"venue":"CVPR","repo":"https://github.com/GISer-WB/MOTIP-2","paper":"https://arxiv.org/abs/2403.16848","local_repo":"third_party/research_refs_phase4n/MOTIP-2","commit":head("third_party/research_refs_phase4n/MOTIP-2"),"license":license_name("third_party/research_refs_phase4n/MOTIP-2"),"inputs":"detector embeddings and historical trajectories","outputs":"ID prediction/association","online_causal":True,"persistent_query":True,"cross_video_correspondence":False,"uses_text_category_id":"trajectory IDs are in-context prompts in original task; forbidden as semantic features","reusable":"history-conditioned association formulation and trajectory memory","reject":"numeric identity prompts must be removed; no unknown-category correspondence","official_command":"bash scripts/train.sh (repo-specific configs)"},
      {"name":"COVTrack","year":2025,"venue":"ICCV","repo":"https://github.com/zekunqian/COVTrack","paper":"https://openaccess.thecvf.com/content/ICCV2025/html/Qian_Continuous_Open-Vocabulary_Tracking_via_Adaptive_Multi-Cue_Fusion_ICCV_2025_paper.html","local_repo":"third_party/research_refs_phase4n/COVTrack","commit":head("third_party/research_refs_phase4n/COVTrack"),"license":license_name("third_party/research_refs_phase4n/COVTrack"),"inputs":"detector proposals, appearance/motion/semantic cues and confidence","outputs":"open-vocabulary tracks and cue-fusion scores","online_causal":True,"persistent_query":False,"cross_video_correspondence":False,"uses_text_category_id":"semantic cue/category-aware prompt exists; excluded","reusable":"confidence, momentum appearance and motion cue separation","reject":"depends on external open-vocabulary detector and semantic cue; not TrackOCD correspondence","official_command":"python run_later.py"},
      {"name":"TRACT","year":2025,"venue":"ICCV","repo":"https://github.com/Nathan-Li123/TRACT","paper":"https://openaccess.thecvf.com/content/ICCV2025/html/Li_Attention_to_Trajectory_Trajectory-Aware_Open-Vocabulary_Tracking_ICCV_2025_paper.html","local_repo":"third_party/TRACT","commit":head("third_party/TRACT"),"license":license_name("third_party/TRACT/masa"),"inputs":"external detector/MASA tracks and trajectory crops; TraCLIP uses CLIP text for classification","outputs":"trajectory-aware association/classification","online_causal":True,"persistent_query":False,"cross_video_correspondence":False,"uses_text_category_id":"TraCLIP explicitly uses CLIP text/category names; excluded","reusable":"trajectory feature aggregation and consistency ideas","reject":"external proposals and text branch; no semantic StateMemory/Commit-Defer","official_command":"see README.md"},
      {"name":"PS-MOT","year":2026,"venue":"ECCV","repo":"https://github.com/xifen523/PS-MOT","paper":"https://arxiv.org/abs/2606.30476","local_repo":None,"commit":"163e9ee31967e6b043b4d71917e833704cda4d19","license":"MIT (official README)","inputs":"point seeds/pseudo boxes and video frames","outputs":"point-supervised MOT tracks","online_causal":True,"persistent_query":False,"cross_video_correspondence":False,"uses_text_category_id":"no semantic text required, but SAM3 pseudo-label route and modern environment are external","reusable":"temporal feedback/motion/uncertainty supervision ideas","reject":"not cross-video correspondence; official training uses 8 processes and separate SAM3 pseudo-label generation","official_command":"accelerate launch --num_processes=8 train.py ..."},
      {"name":"ObjectRelator","year":2025,"venue":"ICCV","repo":"https://github.com/insait-institute/ObjectRelator","paper":"https://arxiv.org/abs/2506.05856","local_repo":None,"commit":"59f79d5d0fa5cfc7169b6737fd414c25d1ed83a6","license":"Apache-2.0","inputs":"cross-view images/objects and multimodal cues","outputs":"cross-view object segmentation/relations","online_causal":False,"persistent_query":False,"cross_video_correspondence":True,"uses_text_category_id":"MCFuse introduces text modality; excluded","reusable":"object-level consistency objective only","reject":"static ego/exo segmentation, no MOT lifecycle or causal controller","official_command":"see repository train/eval scripts"},
      {"name":"C3Po","year":2025,"venue":"NeurIPS","repo":"https://github.com/c3po-correspondence/C3Po","paper":"https://arxiv.org/abs/2503.11135","local_repo":None,"commit":"21254a078435451e99d2feabd5db9334c02d8483","license":"MIT (official repository license)","inputs":"paired cross-view images/geometric data","outputs":"pointmap correspondences and poses","online_causal":False,"persistent_query":False,"cross_video_correspondence":True,"uses_text_category_id":"no category text in pointmap core","reusable":"dense correspondence/geometry alignment concept","reject":"static geometric/photo-plan task; large 8-process training and no MOT lifecycle","official_command":"torchrun --nproc_per_node 8 train.py ..."},
    ]
    result={"schema_version":"phase81p.official_method_audit.v1","created_utc":datetime.datetime.now(datetime.timezone.utc).isoformat(),"network_verified":True,"methods":methods,"selection":"Implement TrackOCD-compatible causal association using MOTIP-2 history-conditioned association, COVTrack confidence/motion separation and TRACT trajectory aggregation; do not import their ID/text semantic shortcuts.","sealed_accessed":False}
    OUT.parent.mkdir(parents=True,exist_ok=True); tmp=OUT.with_name('.'+OUT.name+'.tmp'); tmp.write_text(json.dumps(result,indent=2,sort_keys=True)+'\n'); os.replace(tmp,OUT); print(json.dumps(result,indent=2))
if __name__=='__main__': main()
