#!/usr/bin/env python3
"""Compute read-only proposal/continuity diagnostics for Phase71 predictions.

The evaluator output is generated by the pinned OVTR full-sequence evaluator;
this script only computes transparent IoU/top-k summaries against the TRAIN/
validation annotation.  It never feeds annotations to the model and does not
touch held/Q1/DEV+/public labels.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import pathlib
import statistics
import tempfile
from collections import defaultdict
from typing import Any, Dict, List, Sequence, Tuple

ROOT = pathlib.Path(__file__).resolve().parents[2]
DEFAULT_TAG = "formal1_tco_serial"
DEFAULT_GT = ROOT / "data/external_annotations/ovtr/validation_ours_v1.json"


def atomic_json(path: pathlib.Path, obj: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(prefix=path.name + ".", suffix=".tmp", dir=str(path.parent))
    try:
        with os.fdopen(fd, "w") as f:
            json.dump(obj, f, indent=2, sort_keys=True)
            f.write("\n")
            f.flush()
            os.fsync(f.fileno())
        os.replace(tmp, path)
    finally:
        if os.path.exists(tmp):
            os.unlink(tmp)


def sha256(path: pathlib.Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def xywh_to_xyxy(b: Sequence[float]) -> Tuple[float, float, float, float]:
    x, y, w, h = map(float, b[:4])
    return x, y, x + max(0.0, w), y + max(0.0, h)


def iou(a: Sequence[float], b: Sequence[float]) -> float:
    ax1, ay1, ax2, ay2 = xywh_to_xyxy(a)
    bx1, by1, bx2, by2 = xywh_to_xyxy(b)
    ix1, iy1, ix2, iy2 = max(ax1, bx1), max(ay1, by1), min(ax2, bx2), min(ay2, by2)
    iw, ih = max(0.0, ix2 - ix1), max(0.0, iy2 - iy1)
    inter = iw * ih
    aa = max(0.0, ax2 - ax1) * max(0.0, ay2 - ay1)
    bb = max(0.0, bx2 - bx1) * max(0.0, by2 - by1)
    den = aa + bb - inter
    return inter / den if den > 0 else 0.0


def load_gt(path: pathlib.Path):
    with path.open() as f:
        d = json.load(f)
    gt = defaultdict(list)
    images = {}
    for im in d.get("images", []):
        images[int(im["id"])] = im
    for ann in d.get("annotations", []):
        if ann.get("iscrowd", 0):
            continue
        gt[int(ann["image_id"])].append(ann)
    return gt, images, d


def summarize(gt, images, pred_path: pathlib.Path, topks=(1, 5, 20, 100, 0)) -> Dict[str, Any]:
    with pred_path.open() as f:
        records = json.load(f)
    pred = defaultdict(list)
    for r in records:
        if "image_id" in r and "bbox" in r:
            pred[int(r["image_id"])].append(r)
    gt_rows = sum(len(v) for v in gt.values())
    out: Dict[str, Any] = {
        "prediction_path": str(pred_path.resolve()),
        "prediction_bytes": pred_path.stat().st_size,
        "prediction_sha256": sha256(pred_path),
        "prediction_records": len(records),
        "prediction_images": len(pred),
        "gt_images": len(gt),
        "gt_rows": gt_rows,
        "topk": {},
    }
    for k in topks:
        hits = {t: 0 for t in (0.3, 0.5, 0.7)}
        best_values: List[float] = []
        for image_id, anns in gt.items():
            ps = sorted(pred.get(image_id, []), key=lambda z: float(z.get("score", 0.0)), reverse=True)
            if k > 0:
                ps = ps[:k]
            for ann in anns:
                best = max((iou(ann["bbox"], p["bbox"]) for p in ps), default=0.0)
                best_values.append(best)
                for t in hits:
                    if best >= t:
                        hits[t] += 1
        n = max(gt_rows, 1)
        out["topk"][str(k)] = {
            "thresholds": {f"{t:.1f}": {"matched_rows": hits[t], "recall": hits[t] / n} for t in hits},
            "mean_best_iou": statistics.fmean(best_values) if best_values else 0.0,
            "median_best_iou": statistics.median(best_values) if best_values else 0.0,
        }
    # Diagnostic track continuity proxy, not HOTA/IDF1.
    by_track = defaultdict(list)
    for image_id, anns in gt.items():
        frame = int(images.get(image_id, {}).get("frame_id", images.get(image_id, {}).get("frame_index", 0)))
        video = int(images.get(image_id, {}).get("video_id", -1))
        ps = pred.get(image_id, [])
        for ann in anns:
            best = max((iou(ann["bbox"], p["bbox"]) for p in ps), default=0.0)
            tid = int(ann.get("track_id", ann.get("instance_id", -1)))
            by_track[(video, tid)].append((frame, best))
    details = []
    for (video, tid), vals in by_track.items():
        vals.sort()
        hits = [int(v >= 0.5) for _, v in vals]
        longest = cur = 0
        for h in hits:
            cur = cur + 1 if h else 0
            longest = max(longest, cur)
        details.append({"video_id": video, "track_id": tid, "frames": len(vals), "reliable_frames": sum(hits), "reliable_fraction": sum(hits) / max(1, len(vals)), "longest_reliable_run": longest})
    out["track_continuity_proxy"] = {
        "definition": "class-agnostic IoU>=0.5 frame proxy; not TrackEval",
        "gt_tracks": len(details),
        "mean_reliable_fraction": statistics.fmean(x["reliable_fraction"] for x in details) if details else 0.0,
        "median_reliable_fraction": statistics.median(x["reliable_fraction"] for x in details) if details else 0.0,
        "mean_longest_reliable_run": statistics.fmean(x["longest_reliable_run"] for x in details) if details else 0.0,
        "tracks_reliable_at_least_once": sum(x["reliable_frames"] > 0 for x in details),
        "details": details,
    }
    return out


def prepare_layout(root: pathlib.Path, tag: str, fold: int, pred: pathlib.Path, te_gt: pathlib.Path) -> Dict[str, str]:
    tracker = root / "trackeval" / "trackers" / f"fold_{fold}" / "data" / "tao_track.json"
    gt = root / "trackeval" / "gt" / "validation.json"
    tracker.parent.mkdir(parents=True, exist_ok=True)
    gt.parent.mkdir(parents=True, exist_ok=True)
    for dst, src in ((tracker, pred.resolve()), (gt, te_gt.resolve())):
        if dst.exists() or dst.is_symlink():
            if dst.is_symlink() and os.path.realpath(dst) == str(src):
                continue
            raise RuntimeError(f"refusing to overwrite existing path: {dst}")
        tmp = dst.with_name(dst.name + ".tmp")
        if tmp.exists() or tmp.is_symlink():
            tmp.unlink()
        os.symlink(str(src), tmp)
        os.replace(tmp, dst)
    return {"tracker": str(tracker), "gt": str(gt)}


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--tag", default=DEFAULT_TAG)
    ap.add_argument("--checkpoint-tag", default="formal1")
    ap.add_argument("--gt-json", type=pathlib.Path, default=DEFAULT_GT)
    ap.add_argument("--trackeval-gt", type=pathlib.Path, default=ROOT / "third_party/TrackEval/data/gt/tao/tao_validation/validation.json")
    args = ap.parse_args()
    gt, images, _ = load_gt(args.gt_json)
    root = ROOT / "outputs/iclr27_phase71/validation" / args.tag
    metrics_dir = ROOT / "outputs/iclr27_phase71/metrics" / args.tag
    aggregate = {"protocol": "trackocd_phase71_train_validation_full_sequence", "tag": args.tag, "checkpoint_tag": args.checkpoint_tag, "gt_json": str(args.gt_json.resolve()), "folds": {}}
    for fold in range(4):
        pred = root / f"fold_{fold}/teta_results/tao_track.json"
        if not pred.is_file() or pred.stat().st_size == 0:
            raise FileNotFoundError(pred)
        rec = summarize(gt, images, pred)
        rec["fold"] = fold
        rec["trackeval_layout"] = prepare_layout(root, args.tag, fold, pred, args.trackeval_gt)
        atomic_json(metrics_dir / f"fold_{fold}.json", rec)
        aggregate["folds"][str(fold)] = rec
    for k in ("1", "5", "20", "100", "0"):
        vals = [aggregate["folds"][str(f)]["topk"][k]["thresholds"]["0.5"]["recall"] for f in range(4)]
        aggregate.setdefault("aggregate", {}).setdefault("topk_iou05_recall", {})[k] = {"mean": statistics.fmean(vals), "folds": vals}
    aggregate["aggregate"]["track_continuity_proxy_mean"] = statistics.fmean([aggregate["folds"][str(f)]["track_continuity_proxy"]["mean_reliable_fraction"] for f in range(4)])
    aggregate["sealed_public_q1_accessed"] = False
    aggregate["labels_used_for_model"] = False
    atomic_json(metrics_dir / "aggregate.json", aggregate)
    print(json.dumps({"tag": args.tag, "folds": list(aggregate["folds"]), "top20_iou05": aggregate["aggregate"]["topk_iou05_recall"]["20"]}, indent=2))


if __name__ == "__main__":
    main()
